name: Build and Deploy to NekoWeb

on:    
  workflow_run:
    workflows: ["Update stats"]
    types: [completed]

  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy
        uses: Pufikas/deploytonekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: "pufikas.nekoweb.org"
          nekoweb-username: "pufikas"
          ignore-paths: "assets/bg, assets/cursors, assets/fonts, assets/misc, assets/themes, assets/webring"
