name: Update stats

on:
  push:
    branches: [main] # refresh on push
  schedule:
    - cron: "0 * * * *" # hourly

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch APIs data and update JSON
        run: |
          node src/scripts/utils/update_stats.js

      - name: Commit updated stats.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/data/stats.json
          git commit -m "update stats.json"
          git push
